#!/bin/bash
# ThinkPad E16 G2 - Universal Hybrid - dla opornych plikó kodowanych handbrake (Samsung-Ready)
# Max Speed + Human Readable Time + Terminal Stay

QUALITY="25"

for input in "$@"; do
    file=$(echo "$input" | sed 's|^file://||')
    [ ! -f "$file" ] && continue
    
    output="${file%.*}-UNIhybrid.mkv"
    start_time=$(date +%s)

    notify-send -i "dialog-ok" "ThinkPad D-Turbo" "Start: $(basename "$file")"

    # --- KONFIGURACJA LINII FFMPEG ---

# Komenda "Pancerny Hybrid" (Speed x12-x15)
  ffmpeg -init_hw_device vaapi=intel:/dev/dri/renderD128 -filter_hw_device intel \
        -i "$file" \
        -vf "format=nv12,hwupload,scale_vaapi=1280:-2" \
        -c:v hevc_vaapi -qp "$QUALITY" \
        -map 0:v:0 -map 0:a:0 \
        -c:a copy -sn \
        -max_muxing_queue_size 2048 -y "$output"

    # OPCJA 2: WYCISKARKA (Zakomentowana - pod rarytasy typu Vorbis/DTS)
    # ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi \
    #    -i "$file" \
    #    -vf "scale_vaapi=1280:-2" \
    #    -c:v hevc_vaapi -qp "$QUALITY" \
    #    -map 0:v:0 -map 0:a:0 \
    #    -c:a aac -ac 2 -b:a 128k \
    #    -sn -y "$output"

    if [ $? -eq 0 ]; then
        end_time=$(date +%s)
        duration=$(( end_time - start_time ))
        
        # Przeliczanie na minuty i sekundy
        MIN=$(( duration / 60 ))
        SEC=$(( duration % 60 ))
        
        if [ $MIN -eq 0 ]; then
            TIME_DISPLAY="${SEC}s"
        else
            TIME_DISPLAY="${MIN}m ${SEC}s"
        fi

        notify-send -i "dialog-ok" "D-Turbo Gotowe!" "Czas: $TIME_DISPLAY\nRozmiar: $(du -h "$output" | cut -f1)"
        echo -e "\n\e[32m[SUKCES]\e[0m Proces zakończony w $TIME_DISPLAY."
    else
        notify-send -u critical -i "dialog-error" "Błąd D-Turbo" "Sprawdź błędy w terminalu!"
        echo -e "\n\e[31m[BŁĄD]\e[0m Coś poszło nie tak."
    fi
done

echo -e "\nNaciśnij [ENTER], aby zamknąć to okno..."
read  # To zatrzymuje terminal przed zamknięciem
